---
deployment:
  tasks:
    - export DEPLOYPATH=/home/apexium2/my_school_app
    - >-
      /bin/mkdir -p "$DEPLOYPATH/data" "$DEPLOYPATH/tmp" &&
      /bin/cp -R api backend frontend "$DEPLOYPATH/" &&
      /bin/cp app.js package.json index.html .htaccess "$DEPLOYPATH/" &&
      /usr/bin/touch "$DEPLOYPATH/tmp/restart.txt"
